export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const ADD_PATIENT = "ADD_PATIENT"
export const DELETE_PATIENT = "DELETE_PATIENT"
export const DOC_LOGIN = "DOC_LOGIN"
export const COMP_LOGIN = "COMP_LOGIN"

export const  COMP_LOG_OUT = "COMP_LOG_OUT"
export const  DOC_LOG_OUT = "DOC_LOG_OUT"

export const  PASS_PATIENT = "PASS_PATIENT"
export const  DELETE_PASS_PATIENT = "DELETE_PASS_PATIENT"

export const  COMPOUNDER_PROFILE_ACTION = "COMPOUNDER_PROFILE_ACTION"
export const  DOCTOR_PROFILE_ACTION = "DOCTOR_PROFILE_ACTION"



